### PR TITLE
Adding 4 items: P270, P271, P272, P273

### PR DESCRIPTION
**Pull request by tgeisse**
Added myself to the Contributor list

Added the following 4 items:
- P270_HueColorPicker
- P271_CollapsibleText
- P272_CollapsibleView
- P273_ShapeGenerator

Added the items to the ItemsProvider list

### CODE REVIEW

**Comment by jasudev** [comment]
Thank you for your wonderful contribution. Your work will help many people. 👍

**Comment by tgeisse** [comment]
What are your thoughts in making Items publicly usable? For example, one of my new items is a raindrop. The example has a set frame that works for display. I plan to use this item in at least one other Item and the set frame is not usable in that context.

Would you be ok for me to create a P###_Shared_Item that other Items could then invoke?

**Comment by jasudev** [comment]
hi~
I fully understand your intention to increase reusability. I also thought about that issue.
However, I think we need to look at it from the consumer's point of view, not the code provider's point of view. If the code for that item is fragmented, I think there may be confusion. Because it is a collaborative work, such problems are more likely to occur. So, in my opinion, limiting it to fileprivate is fine. :) 
I'm curious what your opinion is.

**Comment by jasudev** [comment]
> I fully understand your intention to increase reusability. I also thought about that issue.
> However, I think we need to look at it from the consumer's point of view, not the code provider's point of view. If the code for that item is fragmented, I think there may be confusion. Because it is a collaborative work, such problems are more likely to occur. So, in my opinion, limiting it to fileprivate is fine. :)
> I'm curious what your opinion is.

hi~
I fully understand your intention to increase reusability. I also thought about that issue.
However, I think we need to look at it from the consumer's point of view, not the code provider's point of view. If the code for that item is fragmented, I think there may be confusion. Because it is a collaborative work, such problems are more likely to occur. So, in my opinion, limiting it to fileprivate is fine. :)
I'm curious what your opinion is.

**Comment by jasudev** [comment]
> What are your thoughts in making Items publicly usable? For example, one of my new items is a raindrop. The example has a set frame that works for display. I plan to use this item in at least one other Item and the set frame is not usable in that context.
> 
> Would you be ok for me to create a P###_Shared_Item that other Items could then invoke?

hi~
I fully understand your intention to increase reusability. I also thought about that issue.
However, I think we need to look at it from the consumer's point of view, not the code provider's point of view. If the code for that item is fragmented, I think there may be confusion. Because it is a collaborative work, such problems are more likely to occur. So, in my opinion, limiting it to fileprivate is fine. :)
I'm curious what your opinion is.

**Comment by tgeisse** [comment]
I got back and forth. I like the fully isolated code snippets because it provides all someone needs to understand the P-item. There is no jumping around or confusion in understanding the whole code. On the other side, there are elements that would be great if available for easy reuse. Examples: the side and bottom control drawers you built and shapes used in items. I am also planning a few items that I would want to use in a couple of items: one to demonstrate the functionality itself and another to show it in a bigger use case.

After giving your question thought, I think I land on the current structure still being the best. If a new p-item wants to use code from an older p-item, it should be copied. Especially if the code being copied is written by a different collaborator.

**Pull request merged**
